//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamoUnits {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DynamoUnitsImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamoUnitsImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamoUnits.DynamoUnitsImages", typeof(DynamoUnitsImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Area_FromDouble_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Area.FromDouble.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Area_FromDouble_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Area.FromDouble.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Area_FromSquareFeet_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Area.FromSquareFeet.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Area_FromSquareFeet_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Area.FromSquareFeet.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Length_FromDouble_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Length.FromDouble.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Length_FromDouble_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Length.FromDouble.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Length_FromFeet_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Length.FromFeet.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Length_FromFeet_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Length.FromFeet.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_ByLatitudeAndLongitude_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.ByLatitudeAndLongitude.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_ByLatitudeAndLongitude_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.ByLatitudeAndLongitude.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_Latitude_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.Latitude.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_Latitude_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.Latitude.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_Location_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.Location.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_Longitude_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.Longitude.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_Longitude_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.Longitude.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_Name_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.Name.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Location_Name_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Location.Name.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit___double_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.-.double-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit___double_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.-.double-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit___SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.-.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit___SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.-.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit___SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.-.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit___SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.-.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Add_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Add.double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_add_double_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.add.double-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_add_double_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.add.double-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Add_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Add.double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_add_SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.add.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_add_SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.add.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Add_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Add.SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_add_SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.add.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_add_SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.add.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Add_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Add.SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Ceiling_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Ceiling.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Ceiling_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Ceiling.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ConvertToHostUnits_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ConvertToHostUnits.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ConvertToHostUnits_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ConvertToHostUnits.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_div_SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.div.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_div_SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.div.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_div_SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.div.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_div_SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.div.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Divide_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Divide.double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Divide_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Divide.double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Divide_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Divide.SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Divide_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Divide.SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Floor_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Floor.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Floor_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Floor.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ge_double_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ge.double-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ge_double_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ge.double-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ge_SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ge.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ge_SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ge.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ge_SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ge.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ge_SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ge.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_gt_double_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.gt.double-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_gt_double_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.gt.double-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_gt_SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.gt.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_gt_SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.gt.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_gt_SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.gt.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_gt_SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.gt.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_le_double_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.le.double-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_le_double_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.le.double-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_le_SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.le.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_le_SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.le.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_le_SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.le.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_le_SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.le.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_lt_double_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.lt.double-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_lt_double_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.lt.double-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_lt_SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.lt.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_lt_SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.lt.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_lt_SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.lt.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_lt_SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.lt.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mod_double_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mod.double-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mod_double_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mod.double-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mod_SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mod.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mod_SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mod.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mod_SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mod.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mod_SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mod.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Modulo_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Modulo.double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Modulo_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Modulo.double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Modulo_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Modulo.SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Modulo_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Modulo.SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mul_double_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mul.double-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mul_double_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mul.double-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mul_SIUnit_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mul.SIUnit-double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mul_SIUnit_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mul.SIUnit-double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mul_SIUnit_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mul.SIUnit-SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_mul_SIUnit_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.mul.SIUnit-SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Round_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Round.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Round_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Round.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_SetValueFromString_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.SetValueFromString.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_SetValueFromString_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.SetValueFromString.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Subtract_double_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Subtract.double.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Subtract_double_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Subtract.double.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Subtract_SIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Subtract.SIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Subtract_SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Subtract.SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ToSIUnit_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ToSIUnit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_ToSIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.ToSIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Value_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Value.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_SIUnit_Value_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.SIUnit.Value.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Volume_FromCubicFeet_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Volume.FromCubicFeet.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Volume_FromCubicFeet_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Volume.FromCubicFeet.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Volume_FromDouble_Large {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Volume.FromDouble.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DynamoUnits_Volume_FromDouble_Small {
            get {
                object obj = ResourceManager.GetObject("DynamoUnits.Volume.FromDouble.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Location_Small {
            get {
                object obj = ResourceManager.GetObject("Location.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SIUnit_Small {
            get {
                object obj = ResourceManager.GetObject("SIUnit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
