//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreNodeModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreNodeModelsImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreNodeModelsImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreNodeModels.CoreNodeModelsImages", typeof(CoreNodeModelsImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_ColorRange_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.ColorRange.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_ColorRange_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.ColorRange.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_CreateList_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.CreateList.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_CreateList_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.CreateList.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_CurveMapperNodeModel_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.CurveMapperNodeModel.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_CurveMapperNodeModel_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.CurveMapperNodeModel.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_DefineData_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.DefineData.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_DefineData_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.DefineData.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_DynamoConvert_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.DynamoConvert.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_DynamoConvert_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.DynamoConvert.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Equals_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Equals.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Equals_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Equals.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Formula_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Formula.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Formula_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Formula.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_FromArray_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.FromArray.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_FromArray_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.FromArray.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_FromObject_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.FromObject.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_FromObject_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.FromObject.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_ApplyFunction_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.ApplyFunction.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_ApplyFunction_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.ApplyFunction.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_CartesianProduct_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.CartesianProduct.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_CartesianProduct_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.CartesianProduct.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Combine_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Combine.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Combine_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Combine.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_ComposeFunctions_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.ComposeFunctions.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_ComposeFunctions_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.ComposeFunctions.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Filter_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Filter.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Filter_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Filter.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_LaceLongest_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.LaceLongest.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_LaceLongest_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.LaceLongest.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_LaceShortest_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.LaceShortest.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_LaceShortest_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.LaceShortest.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Map_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Map.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Map_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Map.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Reduce_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Reduce.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Reduce_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Reduce.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Replace_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Replace.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_Replace_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.Replace.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_ScanList_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.ScanList.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_HigherOrder_ScanList_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.HigherOrder.ScanList.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_BoolSelector_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.BoolSelector.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_BoolSelector_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.BoolSelector.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_ColorPalette_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.ColorPalette.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_ColorPalette_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.ColorPalette.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_CustomSelection_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.CustomSelection.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_CustomSelection_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.CustomSelection.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_DateTime_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.DateTime.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_DateTime_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.DateTime.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_Directory_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.Directory.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_Directory_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.Directory.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_DirectoryObject_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.DirectoryObject.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_DirectoryObject_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.DirectoryObject.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_DoubleInput_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.DoubleInput.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_DoubleInput_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.DoubleInput.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_DoubleSlider_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.DoubleSlider.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_DoubleSlider_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.DoubleSlider.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_Filename_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.Filename.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_Filename_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.Filename.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_FileObject_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.FileObject.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_FileObject_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.FileObject.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_IntegerSlider64Bit_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.IntegerSlider64Bit.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_IntegerSlider64Bit_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.IntegerSlider64Bit.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_StringInput_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.StringInput.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Input_StringInput_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Input.StringInput.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_And_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.And.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_And_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.And.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_Gate_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.Gate.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_Gate_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.Gate.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_Or_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.Or.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_Or_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.Or.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_RefactoredIf_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.RefactoredIf.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_RefactoredIf_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.RefactoredIf.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_ScopedIf_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.ScopedIf.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Logic_ScopedIf_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Logic.ScopedIf.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Range_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Range.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Range_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Range.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Remember_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Remember.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Remember_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Remember.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Sequence_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Sequence.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Sequence_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Sequence.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Watch_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Watch.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_Watch_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.Watch.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_WatchImageCore_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.WatchImageCore.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_WatchImageCore_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.WatchImageCore.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_WebRequest_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.WebRequest.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModels_WebRequest_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModels.WebRequest.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Evaluate_Small {
            get {
                object obj = ResourceManager.GetObject("Evaluate.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Input_Small {
            get {
                object obj = ResourceManager.GetObject("Input.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logic_Small {
            get {
                object obj = ResourceManager.GetObject("Logic.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scripting_Small {
            get {
                object obj = ResourceManager.GetObject("Scripting.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Strings_Small {
            get {
                object obj = ResourceManager.GetObject("Strings.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Units_Small {
            get {
                object obj = ResourceManager.GetObject("Units.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_Small {
            get {
                object obj = ResourceManager.GetObject("View.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
