//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamo.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreNodeModelsWpfImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreNodeModelsWpfImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamo.Wpf.CoreNodeModelsWpfImages", typeof(CoreNodeModelsWpfImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_BarChartNodeModel_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.BarChartNodeModel.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_BarChartNodeModel_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.BarChartNodeModel.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_BasicLineChartNodeModel_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.BasicLineChartNodeModel.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_BasicLineChartNodeModel_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.BasicLineChartNodeModel.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_HeatSeriesNodeModel_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.HeatSeriesNodeModel.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_HeatSeriesNodeModel_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.HeatSeriesNodeModel.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_PieChartNodeModel_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.PieChartNodeModel.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_PieChartNodeModel_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.PieChartNodeModel.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_ScatterPlotNodeModel_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.ScatterPlotNodeModel.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_ScatterPlotNodeModel_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.ScatterPlotNodeModel.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_XYLineChartNodeModel_Large {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.XYLineChartNodeModel.Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoreNodeModelsWpf_Charts_XYLineChartNodeModel_Small {
            get {
                object obj = ResourceManager.GetObject("CoreNodeModelsWpf.Charts.XYLineChartNodeModel.Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
